### PR TITLE
JuMP and Ipopt compat upgrade

### PR DESCRIPTION
**Pull request by fonsp**
Let's see if the tests pass

### CODE REVIEW

**Comment by fonsp** [comment]
Looks like the Ipopt version is still bound by another dependency: https://github.com/ClimateMARGO/ClimateMARGO.jl/actions/runs/3395776825/jobs/5646082485#step:4:61

**Comment by fonsp** [comment]
The latest test run passed with JuMP v1 and Ipopt v1, both at the latest versions! 🎉

Note that we have tests that pin the output of ClimateMARGO: https://github.com/ClimateMARGO/ClimateMARGO.jl/blob/32e66fd5e53ff2aca89b6e397f22b9855d5bcc40/test/runtests.jl#L36 This means that the JuMP and Ipopt upgrades did not change the output of ClimateMARGO, at least not for the functionality we test there.

**Comment by hdrake** [comment]
Wow, that's great news. Thanks for this update Fons!

**Review by hdrake — COMMENTED** [review]
Looks great!

**Pull request merged**
